name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  http: 0.13.5
  lottie: 2.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_svg: ^2.0.1
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/Frame.svg
